
/*
public class MyClass {
	  public static void main(String[ ] args) {
	    try {
	      int[] myNumbers = {1, 2, 3};
	      System.out.println(myNumbers[10]);
	    } catch (Exception e) {
	      System.out.println("Something went wrong.");
	    }
	  }
	}

// the finally would let you execute code after try-catch 
public class MyClass {
	  public static void main(String[] args) {
	    try {
	      int[] myNumbers = {1, 2, 3};
	      System.out.println(myNumbers[10]);
	    } catch (Exception e) {
	      System.out.println("Something went wrong.");
	    } finally {
	      System.out.println("The 'try catch' is finished.");
	    }
	
	    // throw keyword allows you to make a custom made error 
	    
	   < The throw statement is used together with an exception type. There are many exception types 
	    available in Java: ArithmeticException, 
	    FileNotFoundException, ArrayIndexOutOfBoundsException, SecurityException, etc:>
	    
	    public class MyClass {
	    	  static void checkAge(int age) {
	    	    if (age < 18) {
	    	      throw new ArithmeticException("Access denied - You must be at least 18 years old.");
	    	    }
	    	    else {
	    	      System.out.println("Access granted - You are old enough!");
	    	    }
	    	  }

	    	  public static void main(String[] args) {
	    	    checkAge(15); // Set age to 15 (which is below 18...)
	    	  }
	    	}
	    */
